import { Project } from "@/types";

export const mockProjectsData: Project[] = [
  {
    id: "#proj_001",
    name: "Sunrise Heights",
    image: "/images/projects/project1.png",
    location: "Sector 62, Noida",
    type: "Apartments",
    totalUnits: 240,
    soldUnits: 180,
    availableUnits: 60,
    unitStatus: "180 / 240",
    priceRange: "₹65L - ₹1.2Cr",
    completion: 75,
    status: "Under Construction",
    expectedCompletion: "Dec 2025",
    developer: "Sunrise Developers",
    amenities: ["Swimming Pool", "Gym", "Parking", "Garden"],
  },
  {
    id: "#proj_002",
    name: "Palm Residency",
    image: "/images/projects/project2.png",
    location: "Sector 45, Gurgaon",
    type: "Condos",
    totalUnits: 180,
    soldUnits: 165,
    availableUnits: 15,
    unitStatus: "165 / 180",
    priceRange: "₹85L - ₹1.5Cr",
    completion: 100,
    status: "Completed",
    expectedCompletion: "Jan 2024",
    developer: "Palm Builders",
    amenities: ["Club House", "Gym", "Parking", "Security"],
  },
  {
    id: "#proj_003",
    name: "Green Valley",
    image: "/images/projects/project3.png",
    location: "Sector 78, Faridabad",
    type: "Plots",
    totalUnits: 150,
    soldUnits: 45,
    availableUnits: 105,
    unitStatus: "45 / 150",
    priceRange: "₹45L - ₹80L",
    completion: 25,
    status: "Under Construction",
    expectedCompletion: "Jun 2026",
    developer: "Green Developers",
    amenities: ["Park", "Security", "Water Supply", "Electricity"],
  },
  {
    id: "#proj_004",
    name: "Ocean View",
    image: "/images/projects/project1.png",
    location: "Marine Drive, Mumbai",
    type: "Apartments",
    totalUnits: 320,
    soldUnits: 320,
    availableUnits: 0,
    unitStatus: "320 / 320",
    priceRange: "₹2.5Cr - ₹5Cr",
    completion: 100,
    status: "Completed",
    expectedCompletion: "Mar 2023",
    developer: "Ocean Builders",
    amenities: ["Sea View", "Gym", "Pool", "Valet Parking"],
  },
  {
    id: "#proj_005",
    name: "Metro Heights",
    image: "/images/projects/project2.png",
    location: "CP, New Delhi",
    type: "Bungalows",
    totalUnits: 50,
    soldUnits: 12,
    availableUnits: 38,
    unitStatus: "12 / 50",
    priceRange: "₹8Cr - ₹15Cr",
    completion: 0,
    status: "Upcoming",
    expectedCompletion: "Dec 2027",
    developer: "Metro Developers",
    amenities: ["Private Garden", "Parking", "Security", "Power Backup"],
  },
  {
    id: "#proj_006",
    name: "Royal Townhouse",
    image: "/images/projects/project3.png",
    location: "Sector 50, Gurgaon",
    type: "Townhouse",
    totalUnits: 80,
    soldUnits: 65,
    availableUnits: 15,
    unitStatus: "65 / 80",
    priceRange: "₹3.5Cr - ₹6Cr",
    completion: 90,
    status: "Under Construction",
    expectedCompletion: "Aug 2025",
    developer: "Royal Builders",
    amenities: ["Private Parking", "Garden", "Security", "Club House"],
  },
  {
    id: "#proj_007",
    name: "Crystal Condos",
    image: "/images/projects/project1.png",
    location: "Sector 29, Noida",
    type: "Condos",
    totalUnits: 200,
    soldUnits: 180,
    availableUnits: 20,
    unitStatus: "180 / 200",
    priceRange: "₹75L - ₹1.3Cr",
    completion: 85,
    status: "Under Construction",
    expectedCompletion: "Apr 2025",
    developer: "Crystal Developers",
    amenities: ["Swimming Pool", "Gym", "Parking", "Kids Play Area"],
  },
  {
    id: "#proj_008",
    name: "Elite Plots",
    image: "/images/projects/project2.png",
    location: "Sector 85, Faridabad",
    type: "Plots",
    totalUnits: 120,
    soldUnits: 95,
    availableUnits: 25,
    unitStatus: "95 / 120",
    priceRange: "₹35L - ₹65L",
    completion: 60,
    status: "Under Construction",
    expectedCompletion: "Nov 2025",
    developer: "Elite Developers",
    amenities: ["Gated Community", "Security", "Park", "Water Supply"],
  },
  {
    id: "#proj_009",
    name: "Skyline Towers",
    image: "/images/projects/project3.png",
    location: "Sector 44, Gurgaon",
    type: "Apartments",
    totalUnits: 400,
    soldUnits: 350,
    availableUnits: 50,
    unitStatus: "350 / 400",
    priceRange: "₹1.2Cr - ₹2.5Cr",
    completion: 95,
    status: "Under Construction",
    expectedCompletion: "Sep 2025",
    developer: "Skyline Builders",
    amenities: ["Rooftop Pool", "Gym", "Parking", "Shopping Complex"],
  },
  {
    id: "#proj_010",
    name: "Garden Villas",
    image: "/images/projects/project1.png",
    location: "Sector 12, Noida",
    type: "Bungalows",
    totalUnits: 30,
    soldUnits: 8,
    availableUnits: 22,
    unitStatus: "8 / 30",
    priceRange: "₹5Cr - ₹12Cr",
    completion: 40,
    status: "Under Construction",
    expectedCompletion: "Mar 2026",
    developer: "Garden Developers",
    amenities: ["Private Garden", "Swimming Pool", "Security", "Parking"],
  },
];
