import { Lead } from "@/types";

export const mockLeadsData: Lead[] = [
  {
    id: "lead_1034",
    name: "Rahul Sharma",
    email: "rahul.sharma@email.com",
    phone: "+91-9876543210",
    leadSource: "Facebook",
    projectInterested: "Sunrise Heights",
    unitDetails: "Block A | Unit 1003 • Block B | Unit 1002",
    status: "Negotiation",
    leadScore: 8,
    dateCreated: "14 Nov 2024",
  },
  {
    id: "lead_1035",
    name: "Priya Sutar",
    email: "priya.a074@email.com",
    phone: "+91-9876543210",
    leadSource: "Referral",
    projectInterested: "Palm Residency",
    unitDetails: "Block A | Unit 1232 • Block A | Unit 1001",
    status: "Site Visit",
    leadScore: 7,
    dateCreated: "13 Nov 2024",
  },
  {
    id: "lead_1036",
    name: "Aditi Shah",
    email: "aditishah@email.com",
    phone: "+91-9876543210",
    leadSource: "Walkin",
    projectInterested: "Palm Residency",
    unitDetails: "Block B | Unit 1242",
    status: "New",
    leadScore: 5,
    dateCreated: "12 Nov 2024",
  },
  {
    id: "lead_1037",
    name: "Priya Sutar",
    email: "priya.a074@email.com",
    phone: "+91-9876543210",
    leadSource: "Referral",
    projectInterested: "Palm Residency",
    unitDetails: "Block B | Unit 1001 • Block B | Unit 1000",
    status: "Site Visit",
    leadScore: 6,
    dateCreated: "11 Nov 2024",
  },
  {
    id: "lead_1234",
    name: "Rohan Sharma",
    email: "rohansharma@email.com",
    phone: "+91-9876543210",
    leadSource: "Website",
    projectInterested: "Green Valley",
    unitDetails: "Block C | Unit 1234",
    status: "Booked",
    leadScore: 9,
    dateCreated: "10 Nov 2024",
  },
  {
    id: "lead_1004",
    name: "Aastha Bhatiya",
    email: "aasthabhatiya@email.com",
    phone: "+91-9876543210",
    leadSource: "Campaign",
    projectInterested: "Green Valley",
    unitDetails: "Block A | Unit 1001 • Block A | Unit 1004",
    status: "Contacted",
    leadScore: 10,
    dateCreated: "09 Nov 2024",
  },
  {
    id: "lead_1002",
    name: "Priya Sutar",
    email: "priya.a074@email.com",
    phone: "+91-9876543210",
    leadSource: "Referral",
    projectInterested: "Palm Residency",
    unitDetails: "Block A | Unit 1002",
    status: "Site Visit",
    leadScore: 5,
    dateCreated: "08 Nov 2024",
  },
  {
    id: "lead_1456",
    name: "Amit Kumar",
    email: "amit.kumar@email.com",
    phone: "+91-9876543210",
    leadSource: "Facebook",
    projectInterested: "Ocean View",
    unitDetails: "Block C | Unit 3",
    status: "Booked",
    leadScore: 9,
    dateCreated: "07 Nov 2024",
  },
  {
    id: "lead_1789",
    name: "Neha Gupta",
    email: "neha.gupta@email.com",
    phone: "+91-9876543210",
    leadSource: "Website",
    projectInterested: "Sunrise Heights",
    unitDetails: "Block A | Unit 8",
    status: "Lost",
    leadScore: 2,
    dateCreated: "06 Nov 2024",
  },
  {
    id: "lead_1987",
    name: "Sunita Sharma",
    email: "sunita.sharma@email.com",
    phone: "+91-9876543210",
    leadSource: "Referral",
    projectInterested: "Green Valley",
    unitDetails: "Block A | Unit 7",
    status: "Contacted",
    leadScore: 8,
    dateCreated: "05 Nov 2024",
  },
  {
    id: "lead_2001",
    name: "Vikram Singh",
    email: "vikram.singh@email.com",
    phone: "+91-9876543210",
    leadSource: "Expo",
    projectInterested: "Sunrise Heights",
    unitDetails: "Block B | Unit 205",
    status: "Lost",
    leadScore: 3,
    dateCreated: "04 Nov 2024",
  },
  {
    id: "lead_2002",
    name: "Anita Patel",
    email: "anita.patel@email.com",
    phone: "+91-9876543210",
    leadSource: "Expo",
    projectInterested: "Palm Residency",
    unitDetails: "Block C | Unit 301 • Block C | Unit 302",
    status: "New",
    leadScore: 6,
    dateCreated: "03 Nov 2024",
  },
];
